bigquery: Added support for multi-statement expressions
tobymao/sqlglot pull request #3143
Opened 2024-03-14 07:14 UTC by nadav-botanica

This PR adds support for multiple statements in a single expression for bigquery.
For example, for loops and while loops will now contain the list of statements that they are comprised from.

2024-03-14 08:20 UTC, nadav-botanica commented
For some reason the format checks fail, although I ran ruff format locally with the configuration that's in the pre-commit yml - I would appreciate help with that :)

2024-03-14 17:24 UTC, georgesittas commented
Hey @nadav-botanica, thanks for the PR. I will review soon.

2024-03-14 22:58 UTC, georgesittas commented
> For some reason the format checks fail, although I ran ruff format locally with the configuration that's in the pre-commit yml - I would appreciate help with that :)

FYI this is probably because ruff is probably outdated, you need to `pip install ruff --upgrade` and `make style` afterwards.

2024-03-14 23:38 UTC, tobymao commented
@nadav-botanica really appreciate this pr, it looks like you spent a lot of time on it. in the future, i'd suggest discussing with us first before going off with such a complex implementation.

2024-03-15 15:14 UTC, georgesittas requested changes
Completed the first review pass, check out the comments I left.

@nadav-botanica I think there's value in what you've implemented and we appreciate the effort you put into this. However, this needed to be refactored before requesting a review and, ideally, it should have been split across several PRs. This one is too big to review and it includes several major changes that should be carefully examined.

There are various sections that are redundant and / or inconsistent with the rest of the codebase, which I've underlined in my comments. Please try to follow the existing style for any future PRs and as Toby already mentioned, also reach out in Slack first before starting to work on such a big change.

In any case - thanks a lot for the work!

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/parser.py
> +    def _parse_function_body(self, create_token: Token, extend_props: t.Callable):
Need a return type hint here.

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/dialects/bigquery.py
> +            return this, procedure_body, begin, end_token is not None
I'm not sure I understand this change. Weren't we able to parse _valid_ BQ statements before just fine? What's an example that triggered the need to implement this?

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/dialects/bigquery.py
> +        def while_sql(self, expression: exp.While):
Need return type hints `-> str` for this and the rest of the generator methods.

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/dialects/bigquery.py
> +            return f"WHILE {self.sql(expression, 'this')} DO\n{body}{suffix}"
I don't think we should be hardcoding these newlines here. We have `self.sep()` for this, so that you won't have newlines in non-pretty mode.

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/dialects/bigquery.py
> +                call_args = ",".join([self.sql(e) for e in expression.args.get("call_args", [])])
Let's leverage existing logic such as `self.expressions` instead of manually implementing csv generators.

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/dialects/bigquery.py
> +                call_args = ",".join([self.sql(e) for e in expression.args.get("call_args", [])])
This should leave a white space between the commas, i.e. `arg1, arg2, ...` - but that will be handled by `self.expressions` if you use it.

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/dialects/bigquery.py
> +            comma_separated = ",".join([self.sql(e) for e in expression.args.get("this", [])])
Ditto about `self.expressions`

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/dialects/bigquery.py
> +        def ifstatement_sql(self, expression: exp.IfStatement):
Ditto about leaving some white space. This is hard to read.

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/dialects/bigquery.py
> +            return "\n".join(f"{self.sql(statement)};" for statement in block)
Type hints + `self.sep()` instead of newline here.

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/expressions.py
> +        "else_": False,
Ditto about `else_`.

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/expressions.py
> +    # A block can be empty.
What's an example of this?

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/parser.py
> +    def _parse_function_body(self, create_token: Token, extend_props: t.Callable):
This is ok if we just want to factor out the UDF parsing and reduce noise in `_parse_create`, but I'm not sure about the split between stored procedures and functions. See my other comment in bigquery.py about this.

2024-03-15 15:14 UTC, georgesittas commented on sqlglot/tokens.py
> +    DO = auto()
Nit: alfa-sort these please.

2024-03-15 15:38 UTC, georgesittas commented
I'm closing this for now since it's very difficult to review. Please split this into smaller PRs when you refactor it, thanks.

2024-03-15 15:38 UTC, closed without merging